System.Text.Json.JsonException: 'The JSON value could not be converted to System.String. Path: $.personlista.person[16].personuppgift.uppgift[12].uppgift[0] | LineNumber: 8960 | BytePositionInLine: 17.'